"""
ppo/train.py
=============

The PPO training script.

DQN vs PPO: ON-POLICY vs OFF-POLICY
-----------------------------------
This is the single most important conceptual distinction between this script
and dqn/train.py.

  - DQN is OFF-POLICY. The Q-function it's learning is for the OPTIMAL policy
    (argmax over Q). It can learn from data generated by any policy at all,
    so it stuffs every transition into a giant REPLAY BUFFER and reuses
    each one many times across millions of gradient updates.

  - PPO is ON-POLICY. The policy gradient is only valid for data drawn from
    the CURRENT policy. Once we take an update step, the policy has changed,
    and the old data is (approximately) stale. We therefore COLLECT a fresh
    ROLLOUT, do a small number of updates on it, and THROW IT AWAY.

  - A "rollout" = N_STEPS consecutive env steps under the current policy.
  - A "replay buffer" = a giant random-access bag of historical transitions.

PPO is less sample-efficient (you can't reuse data as aggressively), but it
trains a STOCHASTIC POLICY directly, handles continuous-action spaces
trivially, and is much more stable in practice than DQN-style methods on
games with delicate reward structure.

BOOTSTRAPPING THE VALUE
-----------------------
GAE needs V(s_{T+1}) -- the value of the state AFTER the rollout ends -- to
compute the last advantage. If the rollout ran out of time mid-episode, we
ask the critic for V(s_T): "what's the future value if we keep playing?"
If the rollout ended exactly on a terminal state, the future is 0, so we
pass next_value = 0.

Without this bootstrap, every rollout's last step would have a wildly
biased advantage (we'd treat it as if the episode ended even when it didn't).
"""

import os
import sys
import time

import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from envs.atari_wrappers import make_atari_env
from ppo.agent import PPOAgent
from utils.logger import Logger


# ===================================================================== #
#  HYPERPARAMETERS
# ===================================================================== #

# Atari env id (see dqn/train.py for notes on alternatives).
ENV_ID = "ALE/Pong-v5"

# Total env steps to train. Same scale as DQN -- 2M is the canonical Pong run.
TOTAL_STEPS = 2_000_000

# Rollout length per update. 128 means we collect 128 env steps, then do
# n_epochs * (128 / batch_size) gradient steps on that rollout, then collect
# another 128. Longer rollouts -> lower-variance advantages but more stale
# data per gradient step. Shorter -> the opposite. 128 is the Atari default.
N_STEPS = 128

# Discount factor (see dqn/agent.py).
GAMMA = 0.99
# GAE smoothing (see ppo/agent.py).
GAE_LAMBDA = 0.95
# Adam learning rate. 2.5e-4 is the canonical PPO Atari LR.
LR = 2.5e-4
# PPO clip range.
CLIP_EPSILON = 0.2
# Optimization epochs per rollout.
N_EPOCHS = 4
# Minibatch size.
BATCH_SIZE = 32
# Entropy bonus weight.
ENTROPY_COEF = 0.01
# Value loss weight.
VALUE_COEF = 0.5

# Logging cadence -- print every this many env steps.
EVAL_FREQ = 50_000
# Checkpoint cadence.
SAVE_FREQ = 200_000

CHECKPOINT_DIR = os.path.join(os.path.dirname(__file__), "checkpoints")


def main():
    os.makedirs(CHECKPOINT_DIR, exist_ok=True)

    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    print(f"Using device: {device}")

    env = make_atari_env(ENV_ID)
    n_actions = env.action_space.n
    print(f"Env: {ENV_ID}  n_actions={n_actions}")

    agent = PPOAgent(
        n_actions=n_actions,
        device=device,
        lr=LR,
        gamma=GAMMA,
        gae_lambda=GAE_LAMBDA,
        clip_epsilon=CLIP_EPSILON,
        value_coef=VALUE_COEF,
        entropy_coef=ENTROPY_COEF,
        n_epochs=N_EPOCHS,
        batch_size=BATCH_SIZE,
    )
    logger = Logger()

    obs, info = env.reset(seed=0)
    obs = np.asarray(obs, dtype=np.float32)

    total_steps = 0
    last_info = {}
    start_time = time.time()

    # Outer loop: ROLLOUT, then UPDATE, then ROLLOUT, then UPDATE...
    while total_steps < TOTAL_STEPS:

        # ---------------------------------------------------------- #
        # 1) ROLLOUT COLLECTION
        # We act under the CURRENT policy for N_STEPS and store everything
        # we'll need at update time: (s, a, log_prob, value, r, done).
        # The reason we store value/log_prob at COLLECTION time is that
        # those are computed under pi_old. During the update, we recompute
        # them under pi_new to form the importance ratio.
        # ---------------------------------------------------------- #
        obs_buf       = np.zeros((N_STEPS, 4, 84, 84), dtype=np.float32)
        action_buf    = np.zeros(N_STEPS, dtype=np.int64)
        logprob_buf   = np.zeros(N_STEPS, dtype=np.float32)
        value_buf     = np.zeros(N_STEPS, dtype=np.float32)
        reward_buf    = np.zeros(N_STEPS, dtype=np.float32)
        done_buf      = np.zeros(N_STEPS, dtype=np.float32)

        for t in range(N_STEPS):
            obs_buf[t] = obs

            # Act under the current policy. We do NOT track gradients here;
            # these tensors are stored as constants ("the old policy's view")
            # and the gradient only flows during the update step.
            with torch.no_grad():
                obs_t = torch.from_numpy(obs).unsqueeze(0).to(device)
                action, log_prob, _ent, value = agent.model.get_action(obs_t)

            a = int(action.item())
            action_buf[t]  = a
            logprob_buf[t] = float(log_prob.item())
            value_buf[t]   = float(value.item())

            next_obs, reward, terminated, truncated, info = env.step(a)
            next_obs = np.asarray(next_obs, dtype=np.float32)

            # We store `terminated` (the TRUE terminal flag), not done. The
            # rationale is the same as in dqn/train.py: a truncation should
            # not zero out the bootstrap, but a true terminal should.
            reward_buf[t] = reward
            done_buf[t]   = float(terminated)

            obs = next_obs

            if terminated or truncated:
                if "episode" in info:
                    logger.log_episode(reward=info["episode"]["r"], step=total_steps + t + 1)
                obs, info = env.reset()
                obs = np.asarray(obs, dtype=np.float32)
                last_info = info

        total_steps += N_STEPS

        # ---------------------------------------------------------- #
        # 2) BOOTSTRAP: V(s_T) for GAE's last step.
        # If the last transition was a true terminal we already reset and
        # `obs` points to a NEW episode -- but done_buf[-1] == 1 will zero
        # out the bootstrap inside compute_gae regardless. So it's fine to
        # always compute V(obs) here.
        # ---------------------------------------------------------- #
        with torch.no_grad():
            obs_t = torch.from_numpy(obs).unsqueeze(0).to(device)
            _logits, next_value = agent.model(obs_t)
            next_value = float(next_value.item())

        # ---------------------------------------------------------- #
        # 3) COMPUTE ADVANTAGES / RETURNS via GAE
        # ---------------------------------------------------------- #
        advantages, returns = agent.compute_gae(
            rewards=reward_buf,
            values=value_buf,
            next_value=next_value,
            dones=done_buf,
        )

        # ---------------------------------------------------------- #
        # 4) UPDATE
        # ---------------------------------------------------------- #
        rollout = {
            "obs":           obs_buf,
            "actions":       action_buf,
            "old_log_probs": logprob_buf,
            "returns":       returns,
            "advantages":    advantages,
        }
        losses = agent.update(rollout)

        # ---------------------------------------------------------- #
        # 5) LOG
        # ---------------------------------------------------------- #
        if total_steps // EVAL_FREQ != (total_steps - N_STEPS) // EVAL_FREQ:
            elapsed = time.time() - start_time
            sps = total_steps / max(elapsed, 1e-6)
            print(
                f"step={total_steps:>9}  "
                f"mean100={logger.get_mean_reward(100):>7.2f}  "
                f"policy_loss={losses['policy_loss']:+.4f}  "
                f"value_loss={losses['value_loss']:.4f}  "
                f"entropy={losses['entropy']:.3f}  "
                f"{sps:.0f} sps"
            )

        # ---------------------------------------------------------- #
        # 6) CHECKPOINT
        # ---------------------------------------------------------- #
        if total_steps // SAVE_FREQ != (total_steps - N_STEPS) // SAVE_FREQ:
            path = os.path.join(CHECKPOINT_DIR, f"step_{total_steps}.pt")
            torch.save(agent.model.state_dict(), path)
            print(f"saved checkpoint -> {path}")

    env.close()
    logger.plot_rewards(os.path.join(CHECKPOINT_DIR, "rewards.png"))
    final = os.path.join(CHECKPOINT_DIR, "final.pt")
    torch.save(agent.model.state_dict(), final)
    print(f"Done. Final model -> {final}")


if __name__ == "__main__":
    main()
