"""
dqn/agent.py
=============

This file holds the LEARNING ALGORITHM. The environment, the buffer, and the
network all serve this object: it owns the parameters and decides how they
change.

THE TWO-NETWORK TRICK
---------------------
Plain Q-learning has the agent update toward a target it itself generates:

        Q(s, a)  <--  r + gamma * max_a' Q(s', a')

If Q is a neural net, both sides depend on the same parameters. Every gradient
step on the left changes the right too, and the target moves out from
underneath you. In practice this causes divergence: Q values explode or
oscillate.

DQN's fix is embarrassingly simple but extremely effective:
  - Keep TWO copies of the network: `q_network` (the one we train) and
    `target_network` (a frozen snapshot we use to compute the bootstrap).
  - The TD target uses target_network, so it does not move with each
    gradient step.
  - Every `target_update_freq` steps we hard-copy q_network's weights into
    target_network. The target lags but is reset often enough to track the
    learner.

It's a cheap stabilizer. Without it, training Atari DQN does not work.

EPSILON-GREEDY EXPLORATION
--------------------------
Q-learning is *off-policy*: it can learn from any data, not just data
generated by the current policy. But we still need to *generate* data, and a
greedy policy that always picks argmax Q would never try anything new.

Epsilon-greedy is the standard fix:
  - With probability epsilon, take a random action.
  - Otherwise, take the greedy action (argmax of Q).

Early in training Q is meaningless, so we want lots of randomness:
epsilon = 1.0. As Q starts to mean something, we want to exploit it more, so
we LINEARLY DECAY epsilon down to ~0.05 over the first ~500k steps. We never
go to 0 -- a small amount of random exploration keeps the agent from getting
stuck in bad habits forever.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from dqn.model import QNetwork


class DQNAgent:
    """The DQN learner: two networks, an optimizer, and the Bellman update."""

    def __init__(
        self,
        n_actions,
        device,
        lr=1e-4,
        gamma=0.99,
        epsilon_start=1.0,
        epsilon_end=0.05,
        epsilon_decay_steps=500_000,
        target_update_freq=1000,
    ):
        self.n_actions = n_actions
        self.device = device
        # gamma is the DISCOUNT FACTOR: how much the agent values future
        # rewards relative to immediate ones. 0.99 means a reward 100 steps
        # away is worth ~37% of an immediate reward. Lower gamma -> myopic
        # (good for sparse-reward short games), higher gamma -> long-horizon
        # planning.
        self.gamma = gamma
        # Linear-decay schedule parameters (used inside select_action).
        self.epsilon_start = epsilon_start
        self.epsilon_end = epsilon_end
        self.epsilon_decay_steps = epsilon_decay_steps
        # How often (in env steps) train.py should call update_target_network.
        # We just store it; the loop in train.py is the thing that ticks.
        self.target_update_freq = target_update_freq

        # ---- The two networks ----
        # q_network: trained on every update step.
        self.q_network = QNetwork(n_actions).to(device)
        # target_network: identical architecture, weights are periodically
        # copied from q_network. Used only to compute the TD target.
        self.target_network = QNetwork(n_actions).to(device)
        # Start them synchronized.
        self.target_network.load_state_dict(self.q_network.state_dict())
        # target_network is NEVER trained directly:
        #   - eval() turns off dropout/batchnorm-style training behaviour
        #     (we don't use either here, but it's good hygiene).
        #   - requires_grad_(False) turns off gradient tracking on its params,
        #     so even if it sneaks into a loss term we won't accumulate grads.
        self.target_network.eval()
        for p in self.target_network.parameters():
            p.requires_grad_(False)

        # Adam is fine for DQN. The original paper used RMSProp; modern
        # implementations almost always use Adam at lr ~1e-4.
        self.optimizer = torch.optim.Adam(self.q_network.parameters(), lr=lr)

    # ------------------------------------------------------------------ #
    # ACTION SELECTION
    # ------------------------------------------------------------------ #
    def _epsilon(self, step):
        """
        Linear schedule:  step 0 -> epsilon_start,
                          step >= decay_steps -> epsilon_end,
                          in between -> linear interpolation.
        """
        # Fraction of the decay we have completed, clamped to [0, 1].
        frac = min(1.0, step / max(1, self.epsilon_decay_steps))
        return self.epsilon_start + frac * (self.epsilon_end - self.epsilon_start)

    def select_action(self, state, step):
        """
        Epsilon-greedy action.

        Args:
            state: torch tensor of shape (4, 84, 84) OR (1, 4, 84, 84).
            step:  current global env step, used to look up epsilon.

        Returns:
            An int in [0, n_actions).
        """
        epsilon = self._epsilon(step)

        # EXPLORATION branch: with probability epsilon, pick uniformly at
        # random. torch.rand gives us a single float in [0, 1).
        if torch.rand(1).item() < epsilon:
            return int(torch.randint(0, self.n_actions, (1,)).item())

        # EXPLOITATION branch: pick argmax over the Q-values for this state.
        # We add a batch dim if the caller didn't, then run a single forward
        # pass with no gradient (we're acting, not learning).
        if state.dim() == 3:
            state = state.unsqueeze(0)  # (4,84,84) -> (1,4,84,84)
        with torch.no_grad():
            q_values = self.q_network(state.to(self.device))  # (1, n_actions)
        return int(q_values.argmax(dim=1).item())

    # ------------------------------------------------------------------ #
    # LEARNING STEP
    # ------------------------------------------------------------------ #
    def update(self, batch):
        """
        One gradient step on a minibatch sampled from the replay buffer.

        We are minimizing the MEAN SQUARED BELLMAN ERROR:
            loss = E[ (Q(s, a) - target)^2 ]
        with
            target = r + gamma * max_a' Q_target(s', a') * (1 - done).

        Read the comments line-by-line; every piece corresponds to a part of
        the Bellman equation.
        """
        states, actions, rewards, next_states, dones = batch

        # ---- Current Q estimate: Q(s, a) for the action that was TAKEN ----
        # q_network(states) has shape (B, n_actions). We need to pull out the
        # entry corresponding to the action we actually took.
        # gather(dim=1, index=actions.unsqueeze(1)) does exactly that and
        # gives us shape (B, 1). .squeeze(1) -> (B,).
        q_pred = self.q_network(states).gather(1, actions.unsqueeze(1)).squeeze(1)

        # ---- TD target: r + gamma * max Q_target(s') * (1 - done) ----
        # We don't backprop through the target. torch.no_grad() saves memory
        # and prevents the target_network from being touched by autograd.
        with torch.no_grad():
            # max_a' Q_target(s', a') gives the bootstrapped future value.
            # .max(dim=1) returns (values, indices); we want the values.
            next_q_max = self.target_network(next_states).max(dim=1).values

            # (1 - dones) zeroes out the future-value term when the next
            # state is terminal. A terminal state has NO future reward by
            # definition, so the target collapses to just r.
            #
            # This is the Bellman equation for Q*:
            #     Q*(s, a) = r + gamma * max_a' Q*(s', a')   if not terminal
            #     Q*(s, a) = r                               if terminal
            td_target = rewards + self.gamma * next_q_max * (1.0 - dones)

        # ---- Loss and gradient step ----
        # MSE between current Q estimate and the bootstrapped target.
        # (Many modern implementations use Huber/smooth_l1 here for
        # robustness; the spec asks for MSE, which is fine for Pong.)
        loss = F.mse_loss(q_pred, td_target)

        self.optimizer.zero_grad()
        loss.backward()
        # Optional but very common: clip gradient norm to 10. Prevents the
        # occasional huge update from destabilizing training. The DeepMind
        # code does this; we keep it.
        nn.utils.clip_grad_norm_(self.q_network.parameters(), max_norm=10.0)
        self.optimizer.step()

        return float(loss.item())

    # ------------------------------------------------------------------ #
    # TARGET NETWORK SYNC
    # ------------------------------------------------------------------ #
    def update_target_network(self):
        """
        Hard copy: overwrite target_network's weights with q_network's weights.

        We do this every `target_update_freq` env steps from train.py. The
        target stays stationary in between, which is the WHOLE POINT of
        having two networks (see file docstring).
        """
        self.target_network.load_state_dict(self.q_network.state_dict())
